# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SampleIndoorLocationReporting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MistSDKDR' , '2.0.5'

end
