# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mist-sample-background' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mist-sample-background
	
  pod 'MistSDK’, ‘1.2.0’
  pod 'Kingfisher', '~> 4.0'

end

