# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mist-sample-background-dr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mist-sample-background-dr
  pod 'MistSDKDR'

end
