# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mistsys/mist-vble-ios-sdk.git'

platform :ios, '14.0'

target 'SampleIndoorLocationReporting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleIndoorLocationReporting
	pod 'MistSDK', '4.0.1'                    

end
